package com.concytec.bibliotecaapp.domain;

// Generated 28/07/2014 06:43:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "biblioteca")
public class Categoria implements java.io.Serializable {

	private Integer codCat;
	private String nomCat;
	private String desCat;
	private Set<Recurso> recursos = new HashSet<Recurso>(0);

	public Categoria() {
	}

	public Categoria(String nomCat, String desCat, Set<Recurso> recursos) {
		this.nomCat = nomCat;
		this.desCat = desCat;
		this.recursos = recursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "codCat", unique = true, nullable = false)
	public Integer getCodCat() {
		return this.codCat;
	}

	public void setCodCat(Integer codCat) {
		this.codCat = codCat;
	}

	@Column(name = "nomCat", length = 60)
	public String getNomCat() {
		return this.nomCat;
	}

	public void setNomCat(String nomCat) {
		this.nomCat = nomCat;
	}

	@Column(name = "desCat", length = 80)
	public String getDesCat() {
		return this.desCat;
	}

	public void setDesCat(String desCat) {
		this.desCat = desCat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Recurso> getRecursos() {
		return this.recursos;
	}

	public void setRecursos(Set<Recurso> recursos) {
		this.recursos = recursos;
	}

}
