package com.concytec.bibliotecaapp.domain;

// Generated 28/07/2014 06:43:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prestamo generated by hbm2java
 */
@Entity
@Table(name = "prestamo", catalog = "biblioteca")
public class Prestamo implements java.io.Serializable {

	private PrestamoId id;
	private Usuario usuario;
	private Recurso recurso;
	private Date fecPres;

	public Prestamo() {
	}

	public Prestamo(PrestamoId id, Usuario usuario, Recurso recurso) {
		this.id = id;
		this.usuario = usuario;
		this.recurso = recurso;
	}

	public Prestamo(PrestamoId id, Usuario usuario, Recurso recurso,
			Date fecPres) {
		this.id = id;
		this.usuario = usuario;
		this.recurso = recurso;
		this.fecPres = fecPres;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idePres", column = @Column(name = "idePres", nullable = false)),
			@AttributeOverride(name = "docIdeUsu", column = @Column(name = "docIdeUsu", nullable = false, length = 8)),
			@AttributeOverride(name = "ideRec", column = @Column(name = "ideRec", nullable = false)) })
	public PrestamoId getId() {
		return this.id;
	}

	public void setId(PrestamoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "docIdeUsu", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ideRec", nullable = false, insertable = false, updatable = false)
	public Recurso getRecurso() {
		return this.recurso;
	}

	public void setRecurso(Recurso recurso) {
		this.recurso = recurso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecPres", length = 0)
	public Date getFecPres() {
		return this.fecPres;
	}

	public void setFecPres(Date fecPres) {
		this.fecPres = fecPres;
	}

}
