package com.concytec.bibliotecaapp.domain;

// Generated 28/07/2014 06:43:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrestamoId generated by hbm2java
 */
@Embeddable
public class PrestamoId implements java.io.Serializable {

	private int idePres;
	private String docIdeUsu;
	private int ideRec;

	public PrestamoId() {
	}

	public PrestamoId(int idePres, String docIdeUsu, int ideRec) {
		this.idePres = idePres;
		this.docIdeUsu = docIdeUsu;
		this.ideRec = ideRec;
	}

	@Column(name = "idePres", nullable = false)
	public int getIdePres() {
		return this.idePres;
	}

	public void setIdePres(int idePres) {
		this.idePres = idePres;
	}

	@Column(name = "docIdeUsu", nullable = false, length = 8)
	public String getDocIdeUsu() {
		return this.docIdeUsu;
	}

	public void setDocIdeUsu(String docIdeUsu) {
		this.docIdeUsu = docIdeUsu;
	}

	@Column(name = "ideRec", nullable = false)
	public int getIdeRec() {
		return this.ideRec;
	}

	public void setIdeRec(int ideRec) {
		this.ideRec = ideRec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrestamoId))
			return false;
		PrestamoId castOther = (PrestamoId) other;

		return (this.getIdePres() == castOther.getIdePres())
				&& ((this.getDocIdeUsu() == castOther.getDocIdeUsu()) || (this
						.getDocIdeUsu() != null
						&& castOther.getDocIdeUsu() != null && this
						.getDocIdeUsu().equals(castOther.getDocIdeUsu())))
				&& (this.getIdeRec() == castOther.getIdeRec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdePres();
		result = 37 * result
				+ (getDocIdeUsu() == null ? 0 : this.getDocIdeUsu().hashCode());
		result = 37 * result + this.getIdeRec();
		return result;
	}

}
