package com.concytec.bibliotecaapp.domain;

// Generated 28/07/2014 06:43:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", catalog = "biblioteca")
public class TipoUsuario implements java.io.Serializable {

	private Integer ideTipUsu;
	private String nomTipUsu;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public TipoUsuario() {
	}

	public TipoUsuario(String nomTipUsu, Set<Usuario> usuarios) {
		this.nomTipUsu = nomTipUsu;
		this.usuarios = usuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ideTipUsu", unique = true, nullable = false)
	public Integer getIdeTipUsu() {
		return this.ideTipUsu;
	}

	public void setIdeTipUsu(Integer ideTipUsu) {
		this.ideTipUsu = ideTipUsu;
	}

	@Column(name = "nomTipUsu", length = 20)
	public String getNomTipUsu() {
		return this.nomTipUsu;
	}

	public void setNomTipUsu(String nomTipUsu) {
		this.nomTipUsu = nomTipUsu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
